### ISSUE TITLE
Καθαρισμός δεδομένων

### ISSUE THREAD

**Issue by patiosga** [ekevosm/AutoSolar-System#1]
Καλησπέρα σας,

Σε συνέχεια της δια ζώσης επικοινωνίας μας σχετικά με τη διεύρυνση των δυνατοτήτων του συγκεκριμένου project προς την κατεύθυνση της τεχνητής νοημοσύνης και της μηχανικής μάθησης έχω να προτείνω μερικές ιδέες.
Το πρώτο βήμα για την υλοποίηση τέτοιων αλγορίθμων στα δεδομένα παραγωγής ηλεκτρικής ενέργειας που προκύπτουν από τους έξυπνους μετρητές είναι ο καθαρισμός τους από ακραίες τιμές. Χρησιμοποιώντας στατιστική ανάλυση μπορώ να αφαιρέσω τις τιμές που απέχουν πάνω 2 με 2.5 τυπικές αποκλείσεις από τη μέση τιμή των δεδομένων ενός σχετικά μικρού χρονικού διαστήματος (διάστημα τέτοιο ώστε να μη δικαιολογούνται μεγάλες αποκλείσεις στις τιμές παραγωγής ενέργειας). 
Η παραπάνω διαδικασία μπορεί να διευκολύνει τη μελλοντική υλοποίηση ενός συστήματος πρόβλεψης παραγωγής ενέργειας από το φωτοβολταϊκό πάνελ.

Φιλικά,
Γιώργος Πατιώς

**Comment by ekevosm** [comment]
Γεια σου Γιώργο,

Ευχαριστούμε για την επικοινωνία. Το ζήτημα που περιγράφεις, αφορά στην  επόμενη αναβάθμιση που θέλουμε να προσθέσουμε στο project μας για το οποίο ο καθαρισμός των δεδομένων είναι απαραίτητος. 
Τα δεδομένα παραγωγής και κατανάλωσης ενέργειας αποθηκεύονται ως χρονοσειρές, δηλαδή δυάδες από ένα timestamp και μια τιμή.  Για τη δικιά σου διευκόλυνση μπορείς να θεωρήσεις ότι τα δεδομένα εξάγονται σε ένα αρχείο json. 
Θα προτιμούσαμε να γράψεις τον κώδικα σε python, καθώς είναι μια γλώσσα που έχουμε χρησιμοποιήσει προηγουμένως στο project μας. Ακόμη, ό,τι αρχείο κώδικα θες, να το κάνεις commit μέσα στον φάκελο raspberryPi_code, διότι εκεί αποθηκεύουμε τον κώδικα που θα τρέξει σε αυτή τη συσκευή. 
Είμαστε στη διάθεση σου αν χρειαστείς οποιαδήποτε άλλη πληροφορία.

**Comment by patiosga** [comment]
Καλησπέρα, χαίρομαι που η ιδέα μου σας φάνηκε χρήσιμη. Έχω ήδη έτοιμες κάποιες σχετικές συναρτήσεις σε python και μπορώ εύκολα να τις προσαρμόσω για να παίρνουν τα δεδομένα από αρχεία με json. Θα ανεβάσω σύντομα τον κώδικά μου για να μου πείτε αν θα χρειαστείτε οποιαδήποτε προσθήκη ή αλλαγή.
